spin_manifest_version = 2

[application]
name = "l3xodus"
version = "0.2.0"
authors = ["tyler-harpool <tylerharpool@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "l3xodus"

[component.l3xodus]
source = "target/wasm32-wasi/release/l3xodus.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]

[component.l3xodus.build]
command = "cargo leptos build --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[[trigger.http]]
route = "/pkg/..."
component = "pkg"

[component.pkg]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
files = [{ source = "target/site/pkg", destination = "/" }]
